version: '3.3'

services:
  jenkins_controller:
    build:
      context: ./controller
    container_name: jenkins_controller
    ports:
      - 8092:8080 #web port
      - 50000:50000 #agent port
    volumes:
      - jenkins_controller:/var/jenkins_controller
      - ./jenkins.yaml:/var/jenkins_controller/jenkins.yaml
      - ../../jenkins-automation:/qa/jenkins-automation
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_controller/jenkins.yaml
  jenkins_slave:
    image: eeacms/jenkins-slave  #will be renamed to jenkins-agent soon
    container_name: jenkins_agent
    environment:
      - JAVA_OPTS=-Xmx2048m
      - JENKINS_MASTER=http://jenkins_controller:8080
      - JENKINS_LABELS=simple_agent
      - JENKINS_NAME=worker
      - JENKINS_USER=admin
      - JENKINS_PASS=admin
      - JENKINS_RETRY=10
      - JENKINS_DEBUG_MODE=true
    volumes:
      - ../../jenkins-automation:/qa/jenkins-automation
volumes:
  jenkins_controller:
